# Generated by Django 3.2.6 on 2021-08-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onefittabel',
            name='rank',
            field=models.CharField(default='-', max_length=3),
        ),
    ]
