# Generated by Django 3.2.6 on 2021-08-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataStore', '0002_onefittabel_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='onefittabel',
            name='user_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
