# Generated by Django 3.2.6 on 2021-08-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataStore', '0003_onefittabel_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onefittabel',
            name='rank',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
