# Generated by Django 3.2.6 on 2021-08-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataStore', '0004_alter_onefittabel_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onefittabel',
            name='rank',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='onefittabel',
            name='total_calories_burned',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
